server:
  port: 8085
  servlet:
    context-path: /school

spring:
  application:
    name: school-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/school-service?authSource=admin

application:
  language: "default"