server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      routes:
        - id: identity
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: score
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/college-exam-score/**
          filters:
            - StripPrefix=2
        - id: school
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/school/**
          filters:
            - StripPrefix=2
