server:
  port: 8083
  servlet:
    context-path: /post

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin

app:
  services:
    profile:
      url: http://localhost:8081/profile
    school:
      url: http://localhost:8085/school
