server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/fallback
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1

      routes:
        - id: identity
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**

        - id: profile
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**

        - id: notification
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**

        - id: post
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**

        - id: score
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/college-exam-score/**

        - id: school
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/school/**

springdoc:
  api-docs:
    enabled: true
    group:
      enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Identity Service
        url: ${app.api-prefix}/identity/v3/api-docs
      - name: Notification Service
        url: ${app.api-prefix}/notification/v3/api-docs
      - name: Profile Service
        url: ${app.api-prefix}/profile/v3/api-docs
      - name: Post Service
        url: ${app.api-prefix}/post/v3/api-docs
      - name: Score Service
        url: ${app.api-prefix}/college-exam-score/v3/api-docs
      - name: School Service
        url: ${app.api-prefix}/school/v3/api-docs
  paths-to-match: "/**"
  show-actuator: true

resilience4j:
  circuitbreaker:
    instances:
      globalCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
  ratelimiter:
    instances:
      globalRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
