server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  language: "default"

security:
  password:
    encoder:
      strength: 10

jwt:
  signerKey: "g8Fg6sMWOGd8IxDgE9+4EzXz5lQizljjtbMiRUXT9UpC7HOUUQM/5FDgqV4y3a/G"
  valid-duration: 3600
  refreshable-duration: 36000
  strength: 10
  issuer: "nhanx03"
