server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: monitor-admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

