server:
  port: 8084
  servlet:
    context-path: /college-exam-score

spring:
  application:
    name: score-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/score-service?authSource=admin

application:
  language: "default"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always