server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin

app:
  services:
    profile:
      url: http://localhost:8081/profile
    school:
      url: http://localhost:8085/school
application:
  language: "default"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always